name: Katie Kovalcin

baseurl: ""

markdown: redcarpet
redcarpet:
  extensions: ["smart"]

exclude: [
  .git,
  .gitignore,
  .DS_Store,
  CNAME,
  svg-icons,
  svg-decorations,
  scss,
  .sass-cache,
  package.json, 
  Gruntfile.js, 
  node_modules, 
  readme.md
]

excerpt_separator: <!--more-->